apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: device-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: device-registr
    app.kubernetes.io/version: 0.0.1
spec:
  project: test
  source:
    path: charts/device-registry
    repoURL: https://github.com/openshift-app-service-poc/test-stage-station.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: test-app.$INGRESS.xip.io
      version: v3
  destination:
    namespace: test-station
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true